<?xml version="1.0"?>
<robot name="three_link_arm_flat" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- MARK: Inertias and masses -->
  <xacro:property name="inertiaLink1" value="0.186466" />
  <xacro:property name="inertiaLink2" value="0.186466" />
  <xacro:property name="inertiaLink3" value="15.4373" />

  <xacro:property name="massLink1" value="3.07" />
  <xacro:property name="massLink2" value="3.07" />
  <xacro:property name="massLink3" value="41.218" />

  <!-- MARK:  Geometry -->
  <xacro:property name="COMLink1" value="0.207655" />
  <xacro:property name="COMLink2" value="0.207655" />
  <xacro:property name="COMLink3" value="0.966762" />

  <xacro:property name="lengthLink1" value="0.75" />
  <xacro:property name="lengthLink2" value="0.75" />
  <xacro:property name="lengthLink3" value="2" />

  <xacro:property name="radiusLink1" value="0.015" />
  <xacro:property name="radiusLink2" value="0.015" />
  <xacro:property name="radiusLink3" value="0.015" /> 
  <!-- Delete the line above this once you make it not a cylinder -->
  <xacro:property name="heightPayload" value="0.5" />
  <xacro:property name="depthPayload" value="0.35" />

  <!-- MARK: Links -->
  <!-- Used to give the base a prismatic connection to the world (fixed except in y direction) -->
  <link name="world"/>
  <!-- 1 DOF base (joint will be added at bottom)-->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.4 0.4 0.2"/>
      </geometry>

      <origin xyz="0 0 0"/>

      <material name="grey">
        <color rgba="0.6 0.6 0.6 1"/>
      </material>
      
    </visual>
    
    <collision>
      <geometry>
        <box size="0.4 0.4 0.2"/>
      </geometry>

      <origin xyz="0 0 0"/>

    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>

      <mass value="1.0"/>

      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>

    </inertial>

  </link>

  <!-- Link 1 -->
  <link name="link1">
    <visual>
      <geometry>
        <cylinder radius="${radiusLink1}" length="${lengthLink1}"/>
      </geometry>
      <!-- Rotate cylinder so it lies along X-axis -->
      <origin xyz="${lengthLink1 / 2} 0 0" rpy="0 1.5708 0"/>

      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>

    </visual>

    <collision>
      <geometry>
        <cylinder radius="${radiusLink1}" length="${lengthLink1}"/>
      </geometry>

      <origin xyz="${lengthLink1 / 2} 0 0" rpy="0 1.5708 0"/>

    </collision>

    <inertial>
      <origin xyz="${COMLink1} 0 0" rpy="0 0 0"/>
      <mass value="${massLink1}"/>
      <inertia ixx="${inertiaLink1}" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="${inertiaLink1}"/>
    </inertial>
  </link>

  <!-- Link 2 -->
  <link name="link2">
    <visual>
      <geometry>
        <cylinder radius="${radiusLink2}" length="${lengthLink2}"/>
      </geometry>

      <origin xyz="${lengthLink2 / 2} 0 0" rpy="0 1.5708 0"/>

      <material name="green">
        <color rgba="0 1 0 1"/>
      </material>

    </visual>

    <collision>
      <geometry>
        <cylinder radius="${radiusLink2}" length="${lengthLink2}"/>
      </geometry>

      <origin xyz="${lengthLink2 / 2} 0 0" rpy="0 1.5708 0"/>

    </collision>

    <inertial>
      <origin xyz="${COMLink2} 0 0" rpy="0 0 0"/>
      <mass value="${massLink2}"/>
      <inertia ixx="${inertiaLink2}" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="${inertiaLink2}"/>
    </inertial>
  </link>

  <!-- Link 3 -->
  <link name="link3">
    <visual>
      <geometry>
        <box size="${lengthLink3} ${heightPayload} ${depthPayload}"/>
      </geometry>

      <origin xyz="${lengthLink3 / 2} 0 0" rpy="0 0 0"/>

      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>

    </visual>

    <collision>
      <geometry>
        <cylinder radius="${radiusLink3}" length="${lengthLink3}"/>
      </geometry>

      <origin xyz="${lengthLink3 / 2} 0 0" rpy="0 1.5708 0"/>
      
    </collision>

    <inertial>
      <origin xyz="${COMLink3} 0 0" rpy="0 0 0"/>
      <mass value="${massLink3}"/>
      <inertia ixx="${inertiaLink3}" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="${inertiaLink3}"/>
    </inertial>

  </link>

  <!-- MARK: Joints -->
  <!-- Prismatic joints -->
  <joint name="world_to_base" type="prismatic">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 0"/>
    <axis xyz="0 1 0"/> <!-- movement along Y -->
    <limit lower="-5.0" upper="5.0" effort="50" velocity="5.0"/>
  </joint>

  <!-- Revolute joints -->
  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0.2 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100000" velocity="100000" lower="0" upper="3.14"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="${lengthLink1} 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100000" velocity="100000" lower="-1.57" upper="1.57"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <joint name="joint3" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="${lengthLink2} 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100000" velocity="100000" lower="-3.14" upper="1.57"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <!-- MARK: ROS 2 Control -->
  <ros2_control name="GazeboSimSystem" type="system">
    <hardware>
     <plugin>gz_ros2_control/GazeboSimSystem</plugin>
   </hardware>
   <joint name="world_to_base">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
   </joint>

   <joint name="joint1">
      <command_interface name="effort">
        <param name="min">-100000</param>
        <param name="max">100000</param>
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">1.07079632679</param>
      </state_interface>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
      <hardwareInterface>EffortJointInterface</hardwareInterface>

   </joint>

   <joint name="joint2">
      <command_interface name="effort">
        <param name="min">-100000</param>
        <param name="max">100000</param>
      </command_interface>
     <state_interface name="position">
        <param name="initial_value">1.0</param>
     </state_interface>
     <state_interface name="velocity"/>
     <state_interface name="effort"/>
     <hardwareInterface>EffortJointInterface</hardwareInterface>

   </joint>

    <joint name="joint3">
      <command_interface name="effort">
        <param name="min">-100000</param>
        <param name="max">100000</param>
      </command_interface>
     <state_interface name="position">
        <param name="initial_value">-0.55</param>
     </state_interface>
     <state_interface name="velocity"/>
     <state_interface name="effort"/>
     <hardwareInterface>EffortJointInterface</hardwareInterface>

    </joint>
  </ros2_control>

  <!-- MARK: Gazebo Plugin -->
<gazebo>
  <plugin filename="/opt/ros/jazzy/lib/libgz_ros2_control-system.so" name="gz_ros2_control::GazeboSimROS2ControlPlugin">
    <parameters>/home/dwidjaja/Skyforge/src/skyforge_controllers/config/three_link_arm_controllers.yaml</parameters>
  </plugin>
</gazebo>

</robot>

